# Generated by Django 4.1.4 on 2022-12-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Socios',
        ),
    ]
